embedding_model: "mxbai-embed-large"
qa_model: "phi3:14b-medium-128k-instruct-q4_0"
top_k: 3
max_context_length: 96000
system_message: "You are a helpful assistant that is an expert at extracting the most useful information from a given text, answer the User Question with the most relevant information you can find."

ollama_api:
  base_url: "http://localhost:11434/v1"
  api_key: "xxx"

faiss:
  index_file: "faiss_index.pkl"
  documents_file: "documents.pkl"
  metadata_file: "metadata.pkl"
